config/routes.rb
MoveEx::Application.routes.draw do
  get 'sign_in' => "sessions#new", as: 'sign_in'
  get 'log_in'  => "sessions#new", as: 'log_in'
  delete 'log_out' => "sessions#destroy", as: 'log_out'
  delete 'sign_out'=> "sessions#destroy", as: 'sign_out'

  get 'sign_up' => "users#new", as: 'sign_up'

  root :to => "sessions#static"
  get '/'  => "sessions#static"

  get 'addresses' => "users#index"     # no index for addresses

  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  resources :addresses
  resources :user_attributes
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password

  EMAIL_REGEX = /\b[A-Z0-9._%-]+@[A-Z0-9.-]+\.[A-Z]{2,4}\b/i  # from  http://www.regular-expressions.info/regexbuddy/email.html

  has_one :address
  has_many :user_attributes

  before_save :email_downcase
  before_create :create_remember_token

  validates :name, presence: true
  validates :email, presence: true, format:{ with: EMAIL_REGEX }, uniqueness: { case_sensitive: false }
  validates :password, presence: true, length: { minimum: 6 }
  validates :password_confirmation, presence: true

  def add_pair(key,value)
    kv_object = UserAttribute.create( user_id:self.id, key:key, value:value )
  end

  def remove_pair(key)
    kv_object = UserAttribute.where( user_id:self.id, key:key).first
    kv_object.user_id = nil
    kv_object.save
    kv_object
  end

  def get_value_from_key(key)
    UserAttribute.where( user_id: self.id, key: key).first.value
  end

  def get_keys
    key_array = UserAttribute.where( user_id: self.id)
  end

  def has_keys?
    ! UserAttribute.where( user_id: self.id).empty?
  end

  def self.new_remember_token
    SecureRandom.urlsafe_base64
  end

  def self.encrypt( value )
    Digest::SHA1.hexdigest( value.to_s)
  end


  private

  def email_downcase
    if email.present?
      self.email = email.downcase
    end
  end

  def create_remember_token
    self.remember_token = User.encrypt(User.new_remember_token)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :signed_in_user, only: [:index, :show, :edit, :update, :destroy]
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  def index
    @users = User.all
  end

  def show
  end

  def new
    @user = User.new
  end

  def edit
  end

  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render action: 'show', status: :created, location: @user }
      else
        format.html { render action: 'new' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end

  private

  def set_user
    @user = User.find(params[:id])
  end

  def signed_in_user
    redirect_to sign_in_url, notice: "Please sign in." unless signed_in?
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def user_params
    params.require(:user).permit(:name, :email, :password_digest, :password, :password_confirmation)
  end
end

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :password %><br>
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation %><br>
    <%= f.password_field :password_confirmation %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', user_path(@user) %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>
<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.email %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>Sign Up</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<p>
  <table class='user_address'>
    <thead>
      <tr>
        <th>Address</th>
        <th></th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td><%= @user.address.to_s %></td>
        <td>
          <% unless @user.address.nil? %>
            <%= link_to 'Edit Address', edit_address_path(@user.address) %>
          <% else %>
            <%= link_to 'Add Address', new_address_path(@user) %>
          <% end %>
        </td>
      </tr>
    </tbody>
  </table>
</p>

<p>
<table>
  <thead>
    <tr>
      <th>Position</th>
      <th>Key</th>
      <th>Value</th>
      <th></th>
      <th></th>
    </tr>
  </thead>
  <tbody>
  <% @user.user_attributes.each_with_index do |attribute, idx| %>
    <tr>
      <td><%= (idx+1).to_s %></td>
      <td><%= attribute.key %></td>
      <td><%= attribute.value %></td>
      <td><%= link_to 'Edit Pair', edit_user_attribute_path(attribute) %></td>
      <td><%= link_to 'Delete', attribute, method: :delete, data: { confirm: 'Are you sure?' } %></td>
    </tr>
  <% end %>
  </tbody>
</table>
<%= link_to 'Create Key Value Pair', new_user_attribute_path(@user) %>
</p>
<p>
<%= link_to "Edit #{@user.name}", edit_user_path(@user) %> |
<%= link_to 'Back to Users', users_path %>
</p>