config/routes.rb
MoveEx::Application.routes.draw do
  get 'sign_in' => "sessions#new", as: 'sign_in'
  get 'log_in'  => "sessions#new", as: 'log_in'
  delete 'log_out' => "sessions#destroy", as: 'log_out'
  delete 'sign_out'=> "sessions#destroy", as: 'sign_out'

  get 'sign_up' => "users#new", as: 'sign_up'

  root :to => "sessions#static"
  get '/'  => "sessions#static"

  get 'addresses' => "users#index"     # no index for addresses

  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  resources :addresses
  resources :user_attributes
end

app/models/user_attribute.rb
class UserAttribute < ActiveRecord::Base
  belongs_to :user
end

app/controllers/user_attributes_controller.rb
class UserAttributesController < ApplicationController
  before_action :signed_in_user
  before_action :set_attribute, only: [:show, :edit, :update, :destroy]

  def index
    user_id_value = params[:format]
    @user = User.find(user_id_value)
    @attributes = UserAttribute.where(user_id: @user.id)
  end

  def show
  end

  def new
    user_id = params[:format]
    @user = User.find(user_id)
    @attribute = UserAttribute.new
    @attribute.user = @user
  end

  def edit
  end

  def create
    @attribute = UserAttribute.new(user_attribute_params)

    respond_to do |format|
      if @attribute.save
        format.html { redirect_to @attribute, notice: 'Attribute was successfully created.' }
        format.json { render action: 'show', status: :created, location: @attribute }
      else
        format.html { render action: 'new' }
        format.json { render json: @attribute.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|

      if @attribute.update(user_attribute_params)
        format.html { redirect_to @attribute, notice: 'Attribute was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @attribute.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @attribute.destroy
    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end

  private

  def set_attribute
    @attribute = UserAttribute.find(params[:id])
    begin
      @attribute = UserAttribute.find(params[:id])
    rescue
      @attribute = UserAttribute.new
      @user = User.find( params[:user_id] )
      @attribute.user = @user
    end
  end

  def signed_in_user
    redirect_to sign_in_url, notice: "Please sign in." unless signed_in?
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def user_attribute_params
    params.require(:user_attribute).permit(:key, :value, :user_id)
  end
end

app/views/user_attributes/_form.html.erb
<%= form_for(@attribute) do |f| %>
  <% if @attribute.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@attribute.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @attribute.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user %><br>
    <%= f.label @attribute.user.name unless @attribute.user.nil? %>
    <%= f.hidden_field :user_id, value: @attribute.user.id %>
  </div>
  <div class="field">
    <%= f.label :key %><br>
    <%= f.text_field :key %>
  </div>
  <div class="field">
    <%= f.label :value %><br>
    <%= f.text_field :value %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/user_attributes/edit.html.erb
<h1>Editing User Attribute</h1>

<%= render 'form' %>

<%= link_to 'Show', @attribute %> |
<%= link_to 'Back', user_attribute_path %>

app/views/user_attributes/index.html.erb
<h1>User Attributes for <%= @attributes.first.user.name %></h1>

<table>
  <thead>
    <tr>
      <th>Position</th>
      <th>Key</th>
      <th>Value</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @attributes.each_with_index do |attr, idx| %>
      <tr>
        <td><%= idx+1 %></td>
        <td><%= attr.key %></td>
        <td><%= attr.value %></td>
        <td><%= link_to 'Show', attr %></td>
        <td><%= link_to 'Edit', edit_user_attribute_path(attr) %></td>
        <td><%= link_to 'Delete', attr, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Attribute', new_user_attribute_path(@attributes.first.user) %>
<%= link_to 'Back to User', user_path(@attributes.first.user) %>

app/views/user_attributes/new.html.erb
<h1>Create Attribute for <%= @attribute.user.name %></h1>

<%= render 'form' %>

<%= link_to 'Back', user_path(@attribute.user) %>

app/views/user_attributes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @attribute.user.name %>
</p>

<p>
  <strong>Key:</strong>
  <%= @attribute.key %>
</p>

<p>
  <strong>Value:</strong>
  <%= @attribute.value %>
</p>

<p>
 <%= link_to 'Edit Attribute', edit_user_attribute_path(@attribute) %> |
 <%= link_to 'Back to Attributes', user_attributes_path(@attribute.user) %>
</p>